custom_users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.RegisterView.as_view()),
    path('login/', views.AuthLoginView.as_view(), name='login'),
    path('logout/', views.AuthLogoutView.as_view(), name='logout'),
    path('user_list/', views.PostView.as_view(), name='post'),
]

hashtags/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('product_tags/', views.ProductView.as_view()),
    path('product_tags/<int:id>/', views.ProductDetailView.as_view()),
    path('product_music_tags/', views.MusicHastagsViews.as_view()),
]

main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('programm_lang.urls')),
    path('', include('custom_users.urls')),
    path('', include('hashtags.urls')),
]+static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)\
    +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

programm_lang/urls.py
from django.urls import path
from . import views

app_name='langs'
urlpatterns = [
    path('', views.ProgrammLangView.as_view(), name='lang_list'),
    path('lang_detail/<int:id>/', views.ProgramLangDetailView.as_view()),
    path('lang_list/<int:id>/delete/', views.ProgrammLangDropView.as_view()),
    path('lang_list/<int:id>/update/', views.UpdateLangPostView.as_view()),
    path('create_post_lang/', views.CreateLangPostView.as_view()),
    path('add-cooment/', views.createProgrammLangView),
    path('seacrh/', views.SearchView.as_view(), name='search'),
]

custom_users/models.py
from django.db import models

# Create your models here.

hashtags/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100, verbose_name='добавьте хэштег')

    def __str__(self):
        return f'#{self.name}'


class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(blank=True)
    cost = models.PositiveIntegerField()
    tag = models.ManyToManyField(Tag, related_name='content_name')
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.name}-{self.created_at}'

programm_lang/models.py
from django.db import models

class ProgramLang(models.Model):
    ACTUALITY = (
        ('Актуален', 'Актуален'),
        ('50 на 50', '50 на 50'),
        ('Стрем', 'Стрем'),
    )

    title = models.CharField(max_length=30)
    description = models.TextField()
    image = models.FileField(upload_to='', null=True)
    actuality = models.CharField(max_length=100, choices=ACTUALITY, default=ACTUALITY[0], null=True)
    video = models.URLField(null=True)
    created_date_lang = models.DateField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)


    def __str__(self):
        return self.title

class ReviewProgLang(models.Model):
    STARS = (
        ('*', '*'),
        ('**', '**'),
        ('***', '***'),
        ('****', '****'),
        ('*****', '*****'),

    )
    title_lang = models.ForeignKey(ProgramLang, on_delete=models.CASCADE, related_name='review_object')
    text_review = models.TextField()
    rate_stars = models.CharField(max_length=100, choices=STARS)
    created_at = models.DateField(auto_now_add=True)
    def __str__(self):
       return f"Review for {self.title_lang}"

programm_lang/forms.py
from django import forms
from . import models


class ProgramLangForm(forms.ModelForm):
    class Meta:
        model = models.ProgramLang
        fields = '__all__'

class ReviewForm(forms.ModelForm):
    class Meta:
        model = models.ReviewProgLang
        fields = '__all__'

custom_users/views.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse
from django.views.generic import CreateView, ListView
from django.urls import reverse_lazy


# Register
class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = 'users/register.html'
    success_url = '/login/'


# Log IN
class AuthLoginView(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'

    def get_success_url(self):
        return reverse('langs:lang_list')


# user list
class PostView(ListView):
    queryset = User.objects.all()
    template_name = 'users/post.html'

    def get_queryset(self):
        return User.objects.all()


# Logout
class AuthLogoutView(LogoutView):
    next_page = reverse_lazy('users:login')

hashtags/views.py
from django.shortcuts import get_object_or_404
from .models import Tag, Product
from django.views import generic

class ProductView(generic.ListView):
    queryset = Product.objects.filter().order_by('-id')
    template_name = 'hashtags/product.html'

    def get_queryset(self):
        return self.queryset


class MusicHastagsViews(generic.ListView):
    queryset = Product.objects.filter(tag__name='Музыка')
    template_name = 'hashtags/product_music.html'

    def get_queryset(self):
        return self.queryset

class ProductDetailView(generic.DetailView):
    template_name = 'hashtags/product_detail.html'

    def get_object(self, **kwargs):
        product_id = self.kwargs.get('id')
        return get_object_or_404(Product, id=product_id)

programm_lang/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from . import models, forms
from django.views import generic


class ProgrammLangView(generic.ListView):
    template_name = 'programm_lang.html'
    queryset = models.ProgramLang.objects.all()

    def get_queryset(self):
        return models.ProgramLang.objects.all()

class ProgramLangDetailView(generic.DetailView):
    template_name = 'programm_lang_detail.html'

    def get_object(self, **kwargs):
       lang = self.kwargs.get('id')
       return get_object_or_404(models.ProgramLang, id=lang)

class CreateLangPostView(generic.CreateView):
    template_name = 'create_lang.html'
    form_class = forms.ProgramLangForm
    queryset = models.ProgramLang.objects.all()
    success_url = '/'

    def form_valid(self, form):
        print(form.cleaned_data)
        return super(CreateLangPostView, self).form_valid(form=form)

class UpdateLangPostView(generic.UpdateView):
    template_name = 'update_lang.html'
    form_class = forms.ProgramLangForm
    success_url = '/'

    def get_object(self, **kwargs):
        lang = self.kwargs.get('id')
        return get_object_or_404(models.ProgramLang, id=lang)

    def form_valid(self, form):
        return super(UpdateLangPostView, self).form_valid(form=form)

class ProgrammLangDropView(generic.DeleteView):
    template_name = 'confirm_delete.html'
    success_url = '/'

    def get_object(self, **kwargs):
        lang_id = self.kwargs.get('id')
        return get_object_or_404(models.ProgramLang, id=lang_id)

def createProgrammLangView(request):
    method = request.method
    if method == 'POST':
        form = forms.ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponse('<h1>Коммент успешно добавлен</h1>')

    else:
        form = forms.ReviewForm()

    return render(request, 'create_review.html', {'form': form})

class SearchView(generic.ListView):
    template_name = 'programm_lang.html'
    context_object_name = 'lang'
    paginate_by = 5

    def get_queryset(self):
        return models.ProgramLang.objects.filter(title__icontains=self.request.GET.get('q'))

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['q'] = self.request.GET.get('q')
        return context

templates/confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Вы уверенны что хотите дропнуть этот язык?</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <button type="submit">ДА</button>
    <button><a href="/">НЕТ</a></button>
</form>
</body>
</html>

templates/create_lang.html
{% include 'header.html' %}

<form class="decor" action="/create_post_lang/" method="post" enctype="multipart/form-data">
<div class="form-left-decoration"></div>
<div class="form-right-decoration"></div>
<div class="circle"></div>
<div class="form-inner">
<h3>Добавить фильм</h3>
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Сохранить</button>
    <button type="reset">Отмена</button>
</div>
</form>

<style>
    * {
   box-sizing: border-box;
}
body {
   background: #f69a73;
}
.decor {
   position: relative;
   max-width: 400px;
   margin: 50px auto 0;
   background: white;
   border-radius: 30px;
}
.form-left-decoration, .form-right-decoration {
   content: "";
   position: absolute;
   width: 50px;
   height: 20px;
   background: #f69a73;
   border-radius: 20px;
}
.form-left-decoration {
   bottom: 60px;
   left: -30px;
}
.form-right-decoration {
   top: 60px;
   right: -30px;
}
.form-left-decoration:before, .form-left-decoration:after, .form-right-decoration:before, .form-right-decoration:after {
   content: "";
   position: absolute;
   width: 50px;
   height: 20px;
   border-radius: 30px;
   background: white;
}
.form-left-decoration:before {
   top: -20px;
}
.form-left-decoration:after {
   top: 20px;
   left: 10px;
}
.form-right-decoration:before {
   top: -20px;
   right: 0;
}
.form-right-decoration:after {
   top: 20px;
   right: 10px;
}
.circle {
   position: absolute;
   bottom: 80px;
   left: -55px;
   width: 20px;
   height: 20px;
   border-radius: 50%;
   background: white;
}
.form-inner {
   padding: 50px;
}
.form-inner input, .form-inner textarea {
   display: block;
   width: 100%;
   padding: 0 20px;
   margin-bottom: 10px;
   background: #E9EFF6;
   line-height: 40px;
   border-width: 0;
   border-radius: 20px;
   font-family: 'Roboto', sans-serif;
}
.form-inner input[type="submit"] {
   margin-top: 30px;
   background: #f69a73;
   border-bottom: 4px solid #d87d56;
   color: white;
   font-size: 14px;
}
.form-inner textarea {
   resize: none;
}
.form-inner h3 {
   margin-top: 0;
   font-family: 'Roboto', sans-serif;
   font-weight: 500;
   font-size: 24px;
   color: #707981;
}
</style>
{% include 'footer.html' %}

templates/create_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CreateReview</title>
</head>
<body>
<form action="/add-cooment/"  method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <button type="submit">Отправить</button>
  <button type="reset">Отменить</button>
</form>
</body>
</html>

templates/footer.html
<footer class="bg-light text-center text-lg-start">
  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2020 Copyright:
    <a class="text-dark" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
  <!-- Copyright -->
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>

</body>
</html>

templates/hashtags/product.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>TAgs</title>
</head>
<body>
<ol>
    {% for i in object_list %}
    <li>
        <h1>{{i.name}}</h1>
        <a href="/product_tags/{{i.id}}/">Детально</a>
    </li>
    {% endfor %}
</ol>


</body>
</html>

templates/hashtags/product_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
<h1>{{object.name}}</h1>
<p>{{object.cost}}</p>
<p>{{object.created_at}}</p>
<ul>
    {% for i in object.tag.all %}
        <li>
            <h3>#{{ i.name }}</h3>
        </li>
    {% endfor %}
</ul>
</body>
</html>

templates/hashtags/product_music.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ol>
    {% for i in object_list %}
    <li>
        <h1>{{i.name}}</h1>
        <a href="/product_tags/{{i.id}}/">Детально</a>
    </li>
    {% endfor %}
</ol>
</body>
</html>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Навбар</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Главная</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/add-cooment/">Оставьте отзыв</a>
          <a class="nav-link" href="/register/">Создать аккаунт</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Действие
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/create_post_lang/">Добавить</a></li>
            <li><a class="dropdown-item" href="/lang_list/">Удалить</a></li>
            <li><a class="dropdown-item" href="#">Изменить</a></li>
          </ul>
        </li>
      </ul>
      <form action="{% url 'langs:search' %}" method="GET" class="d-flex" role="search">
        <input class="form-control me-2" type="text" name="q" type="search" placeholder="Поиск" aria-label="Поиск">
        <button class="btn btn-outline-success" type="submit">Поиск</button>
      </form>
    </div>
  </div>
</nav>
</body>
</html>

templates/program_lang_list.html
{% include 'header.html' %}

<br><center><span class="badge text-bg-warning"><h1>Топ 3 языка программирования 2023</h1></span></center><br>
<div class="flex">
 {% for i in lang_key %}
    <div class="card" style="width: 18rem;">
      <img src="{{i.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{i.title}}</h5>
        <a href="/lang_list/{{i.id}}/delete/" class="btn btn-primary">Удалить</a>
      </div>
</div>
   {% endfor %}
     </div>
{% include 'footer.html' %}

templates/programm_lang.html
{% include 'header.html' %}

<br><center><span class="badge text-bg-warning"><h1>Топ 3 языка программирования 2023</h1></span></center><br>
<div class="flex">
 {% for i in object_list %}
    <div class="card" style="width: 18rem;">
      <img src="{{i.image.url}}" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title">{{i.title}}</h5>
        <p class="card-text">{{i.description}}</p>
        <a href="/lang_detail/{{i.id}}/" class="btn btn-primary">Подробнее</a>
      </div>
</div>
   {% endfor %}
     </div>
{% include 'footer.html' %}

templates/programm_lang_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Detail</title>
</head>
<body>
    <button><a href="/lang_list/{{object.id}}/update/">Изменить</a></button>
    <button><a href="/lang_list/{{object.id}}/delete/">Удалить</a></button>
    <h1>Детальная инфомация</h1>
    <h2>{{object.title}}</h2>
    <p>{{object.description}}</p>
    <img src="{{object.image.url}}" alt="lang_prog">
    <p>{{object.actuality}}</p>
    <iframe src="{{object.video}}" frameborder="0"></iframe>
    <p>{{object.created_date_lang}}</p>
    <p>{{object.created_at}}</p>

    <table border="2">
        <tr>
            <th>Дата создания отзыва</th> <th>Комент</th> <th>Оценка</th>
        </tr>

        {% for i in object.review_object.all %}
        <tr>
            <td>{{i.created_at}}</td> <td>{{i.text_review}}</td> <td>{{i.rate_stars}}</td>
        </tr>
        {% endfor %}

    </table>

</body>
</html>

templates/update_lang.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Обновить</button>
</form>
</body>
</html>

templates/users/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Авторизация</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Войти</button>
</form>
<a href="/register/">У вас нет аккаунта?</a>
</body>
</html>

templates/users/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Ура вы успешно прошли FaceControl</h1>
<p>Списки приглашенных</p>
<ol>
    {% for i in object_list %}
    <li>
        <h2>{{i.username}}</h2>
    </li>
    {% endfor %}
</ol>
<form action="{% url 'users:login' %}" method="POST">
    {% csrf_token %}
    <button type="submit">Выйти из аккаунта</button>
</form>
</body>
</html>

templates/users/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Регистрация</h1>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit">Регистрация</button>
</form>
</body>
</html>